```yaml
# tech_stack_detector.py
stages:
  - name: Build
    steps:
      - step:
          name: Build and Test
          image: maven:3.8.6-openjdk-17 # Using a specific Maven and JDK version for consistency
          caches:
            - maven # Caching Maven dependencies
          script:
            - echo "Building and testing the Java application..."
            - mvn clean install # Clean, compile, test, and package the application
          artifacts:
            - target/* # Store the built JAR/WAR file as an artifact

  - name: SonarQube Analysis
    steps:
      - step:
          name: SonarQube Analysis
          image: maven:3.8.6-openjdk-17 # Consistent environment
          caches:
            - maven
          script:
            - echo "Running SonarQube analysis..."
            - mvn sonar:sonar -Dsonar.host.url=$SONARQUBE_URL -Dsonar.login=$SONARQUBE_TOKEN # Passing SonarQube URL and token as environment variables
          after_script:
            - echo "SonarQube analysis completed."

  - name: Docker Build and Push
    steps:
      - step:
          name: Build Docker Image
          image: docker:20.10.12 # Using a specific Docker version for build reproducibility
          services:
            - docker # Enabling Docker-in-Docker service
          script:
            - echo "Building Docker image..."
            - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD # Docker login with username and password from environment variables
            - docker build -t $DOCKER_IMAGE_NAME . # Building the Docker image
            - docker push $DOCKER_IMAGE_NAME # Pushing the Docker image to the registry
          after_script:
            - echo "Docker image built and pushed."
```