```yaml
# tech_stack_detector.py
name: React CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Or your preferred Node.js version

      - name: Install Dependencies
        run: npm install # Or yarn install if using Yarn

      - name: Run Tests
        run: npm test # Or yarn test

      - name: Build Production
        run: npm run build # Or yarn build.  Assumes "build" script creates a production-ready artifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-app
          path: build # Or your build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' # Only deploy from main branch

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: react-app
          path: build

      - name: Deploy to Production # Replace with your deployment strategy
        run: |
          echo "Deploying to production..."
          # Add your deployment commands here
          # Example:
          # scp -r build/* user@yourserver.com:/var/www/your-app
          echo "Deployment complete."
```