```yaml
# tech_stack_detector.py
# Pipeline for building and deploying a Java application using Maven.

stages:
  - name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Package
        run: mvn -B package --file pom.xml

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: target
          path: target/*.jar

  - name: Test
    needs: Build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven Verify
        run: mvn -B verify --file pom.xml

  - name: Deploy
    needs: Test
    environment:
      name: Production
      url: your_deployment_url # Replace with your actual deployment URL
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: target
          path: target

      - name: Deploy to Production # Replace with your deployment script
        run: |
          echo "Deploying to Production..."
          # Add your deployment commands here. For example:
          # scp target/*.jar user@your_server:/path/to/deployment/directory/
          # ssh user@your_server "sudo systemctl restart your_service"
```