```yaml
# tech_stack_detector.py
# Pipeline configuration for Java (Maven) project

stages:
  - name: Build
    steps:
      - step:
          name: Checkout Code
          type: git-checkout
          repo: self
  
      - step:
          name: Setup JDK
          image: maven:3.8.6-openjdk-17 # Using a specific Maven and JDK version for reproducibility
          script:
            - echo "Setting up JDK 17" # Explicitly state the JDK version
            - java -version # Verify Java version

      - step:
          name: Maven Build and Test
          image: maven:3.8.6-openjdk-17
          script:
            - echo "Starting Maven build"
            - mvn clean install -DskipTests # Build and skip tests initially to check compilation
            - echo "Maven build completed"
  
  - name: Test
    steps:
      - step:
          name: Run Tests
          image: maven:3.8.6-openjdk-17
          script:
            - echo "Running tests"
            - mvn test # Run unit tests
            - echo "Tests completed"
          after_script:
            - echo "Checking test results"

  - name: SonarQube Analysis
    steps:
      - step:
          name: SonarQube Scan
          image: maven:3.8.6-openjdk-17
          script:
            - echo "Starting SonarQube analysis"
            - mvn sonar:sonar -Dsonar.projectKey=$SONAR_PROJECT_KEY -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN # Using environment variables for SonarQube configuration
            - echo "SonarQube analysis completed"
          after_script:
            - echo "Check SonarQube for quality gate status"
          services:
            - sonarqube  # Declare the SonarQube service

services:
  sonarqube:
    image: sonarqube:lts #Using a stable LTS version of SonarQube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Disable bootstrap checks for easier startup during CI

options:
  docker: true #Enables Docker support in the pipeline
```