```yaml
# tech_stack_detector.py
# Pipeline for building and deploying a Java application using Maven.
# Includes stages for checkout, build, test, and deployment.

stages:
  - checkout
  - build
  - test
  - deploy

checkout:
  stage: checkout
  image: alpine/git:latest
  script:
    - echo "Checking out the code..."
    - git clone $CI_REPOSITORY_URL .
    - echo "Checkout complete."

build:
  stage: build
  image: maven:3.8.6-openjdk-17
  script:
    - echo "Building the application..."
    - mvn clean install -DskipTests
    - echo "Build complete."
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test:
  stage: test
  image: maven:3.8.6-openjdk-17
  script:
    - echo "Running tests..."
    - mvn test
    - echo "Tests complete."
  dependencies:
    - build

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "Logging in to Docker Hub..."
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  script:
    - echo "Building Docker image..."
    - docker build -t $DOCKER_IMAGE_NAME .
    - echo "Pushing Docker image..."
    - docker push $DOCKER_IMAGE_NAME
    - echo "Deployment complete."
  dependencies:
    - build
  only:
    - main # or your main branch name
  variables:
    DOCKER_IMAGE_NAME: $DOCKER_USERNAME/$CI_PROJECT_NAME:$CI_COMMIT_SHA

```