```yaml
# tech_stack_detector.py
# Pipeline for Java (Maven) projects
# Includes build, test, and artifact deployment stages.

stages:
  - name: Build
    steps:
      - step:
          name: Build and Analyze
          image: maven:3.8.5-openjdk-17 # Using a specific maven image for consistency
          caches:
            - maven
          script:
            - echo "Starting build process..."
            - mvn clean install -DskipTests  # Build the project, skipping tests initially
            - echo "Build completed."
  - name: Test
    steps:
      - step:
          name: Unit Tests
          image: maven:3.8.5-openjdk-17
          caches:
            - maven
          script:
            - echo "Running unit tests..."
            - mvn test # Run unit tests
            - echo "Unit tests completed."
  - name: Package
    steps:
      - step:
          name: Package Artifact
          image: maven:3.8.5-openjdk-17
          caches:
            - maven
          script:
            - echo "Packaging artifact..."
            - mvn package # Package the application
            - echo "Artifact packaged."
          artifacts:
            - target/*.jar  # Specify the artifact to be saved

  - name: Deploy
    steps:
      - step:
          name: Deploy to Repository
          image: alpine/git # Using git image for deployment (example)
          script:
            - echo "Deploying artifact..."
            # Replace with your actual deployment script
            # Example: scp target/*.jar user@host:/path/to/deploy/
            - echo "Artifact deployed (Placeholder - Implement actual deployment)"
```
