```yaml
# tech_stack_detector.py
# Pipeline for Java (Maven) projects
stages:
  - name: Build
    steps:
      - step:
          name: Checkout
          type: git-checkout
          repo: ${{repo.FullName}}
          revision: ${{revision}}

      - step:
          name: Set up JDK
          image: maven:3.8.6-openjdk-17
          commands:
            - echo "Installing JDK 17"

      - step:
          name: Maven Build
          image: maven:3.8.6-openjdk-17
          commands:
            - echo "Starting Maven build"
            - mvn clean install -DskipTests # Build the project

  - name: Test
    steps:
      - step:
          name: Run Tests
          image: maven:3.8.6-openjdk-17
          commands:
            - echo "Running tests"
            - mvn test # Execute the tests
          when:
            status: success # Only run if the Build stage was successful

  - name: Package
    steps:
      - step:
          name: Package Artifact
          image: maven:3.8.6-openjdk-17
          commands:
            - echo "Packaging artifact"
            - mvn package # Package the application
          when:
            status: success # Only run if the Test stage was successful

  - name: Deploy
    steps:
      - step:
          name: Deploy to Repository
          image: maven:3.8.6-openjdk-17
          commands:
            - echo "Deploying artifact"
            # Add deployment commands here (e.g., deploy to Maven Central, deploy to a custom repository)
            - echo "Deployment commands go here" #Placeholder
          when:
            status: success # Only run if the Package stage was successful
```