```yaml
# tech_stack_detector.py
# CI/CD pipeline for a React application.
# Uses Node.js for building and testing, and deploys to a static hosting provider (e.g., AWS S3, Netlify).

name: React CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18 # or your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1' # Replace with your AWS region
          S3_BUCKET: 'your-s3-bucket-name' # Replace with your S3 bucket name
        run: |
          npm install -g aws-cli
          aws s3 sync ./build s3://$S3_BUCKET --delete # Ensure to delete old files to prevent caching issues.

```