```yaml
# tech_stack_detector.py
# Pipeline configuration for a React application.
# This pipeline includes linting, building, testing, and deployment stages.

stages:
  - Lint
  - Build
  - Test
  - Deploy

Lint:
  stage: Lint
  image: node:latest
  script:
    - echo "Running linter..."
    - npm install --silent
    - npm run lint
  tags:
    - docker

Build:
  stage: Build
  image: node:latest
  script:
    - echo "Building the application..."
    - npm install --silent
    - npm run build
  artifacts:
    paths:
      - build/
  tags:
    - docker
  dependencies:
    - Lint

Test:
  stage: Test
  image: node:latest
  script:
    - echo "Running tests..."
    - npm install --silent
    - npm run test -- --coverage
  artifacts:
    paths:
      - coverage/
  coverage: '/All files[^|]*\\|[^\\d]*([\\d\\.]+)\\%/'
  tags:
    - docker
  dependencies:
    - Build

Deploy:
  stage: Deploy
  image: alpine/git
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 400 ~/.ssh/id_rsa
    - ssh-keyscan $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - chmod 400 ~/.ssh/known_hosts
  script:
    - echo "Deploying the application..."
    - rsync -avz --delete build/ $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
  environment:
    name: production
    url: $DEPLOY_URL
  only:
    - main
  tags:
    - docker
  dependencies:
    - Test
```